
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ee.x_road.kli_util_v1.producer;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-06T11:37:59.819+01:00
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "Service",
                      portName = "ServiceSoap",
                      targetNamespace = "http://kli-util-v1.x-road.ee/producer",
                      wsdlLocation = "file:WebContent/wsdl/Verkstova.wsdl",
                      endpointInterface = "ee.x_road.kli_util_v1.producer.ServiceSoap")
                      
public class ServiceSoapImpl implements ServiceSoap {

    private static final Logger LOG = Logger.getLogger(ServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see ee.x_road.kli_util_v1.producer.ServiceSoap#listMethods(java.lang.Object body)*
     */
    public ee.x_road.xsd.x_road.ListMethodsResponse listMethods(java.lang.Object body) { 
        LOG.info("Executing operation listMethods");
        System.out.println(body);
        try {
            ee.x_road.xsd.x_road.ListMethodsResponse _return = new ee.x_road.xsd.x_road.ListMethodsResponse();
            ee.x_road.xsd.x_road.ListMethodsResponse.Response _returnResponse = new ee.x_road.xsd.x_road.ListMethodsResponse.Response();
            java.util.List<java.lang.String> _returnResponseItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnResponseItemVal1 = "kli-util-v1.personLookup.v1";
            _returnResponseItem.add(_returnResponseItemVal1);
            _returnResponse.getItem().addAll(_returnResponseItem);
            _return.setResponse(_returnResponse);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ee.x_road.kli_util_v1.producer.ServiceSoap#personLookup(ee.x_road.kli_util_v1.producer.PersonLookup.Request request, java.lang.String consumer, java.lang.String producer, java.lang.String userId, java.lang.String id, java.lang.String service, ee.x_road.kli_util_v1.producer.PersonLookupResponse.Request request1, ee.x_road.kli_util_v1.producer.PersonLookupResponse.Response response, java.lang.String consumer1, java.lang.String producer1, java.lang.String userId1, java.lang.String id1, java.lang.String service1)*
     */
    public void personLookup(ee.x_road.kli_util_v1.producer.PersonLookup.Request request, java.lang.String consumer, java.lang.String producer, java.lang.String userId, java.lang.String id, java.lang.String service, javax.xml.ws.Holder<ee.x_road.kli_util_v1.producer.PersonLookupResponse.Request> request1, javax.xml.ws.Holder<ee.x_road.kli_util_v1.producer.PersonLookupResponse.Response> response, javax.xml.ws.Holder<java.lang.String> consumer1, javax.xml.ws.Holder<java.lang.String> producer1, javax.xml.ws.Holder<java.lang.String> userId1, javax.xml.ws.Holder<java.lang.String> id1, javax.xml.ws.Holder<java.lang.String> service1) { 
        LOG.info("Executing operation personLookup");
        try {
        	consumer1.value = consumer;
        	producer1.value = producer;
        	userId1.value = userId;
        	id1.value = id;
        	service1.value = service;        	
        	
        	int theId = request.getId();
        	
        	ee.x_road.kli_util_v1.producer.PersonLookupResponse.Request request1Value = new ee.x_road.kli_util_v1.producer.PersonLookupResponse.Request();        	
        	request1Value.setId(request.getId());
        	request1.value = request1Value;
        	
        	ee.x_road.kli_util_v1.producer.PersonLookupResponse.Response responseValue = new ee.x_road.kli_util_v1.producer.PersonLookupResponse.Response();
        	
        	Person p = new Person();
        	p.setId(theId);
        	p.setFullName("Test Persónur 2471");
        	p.setEmailAddress("onkur2471@onkrastadni.fo");
        	p.setPhoneNumber("292471");
        	
        	Address a = new Address();
        	a.setAddressLine1("Onkurgøta 2471");
        	a.setCity("Onkurbýur");
        	a.setZipCode("101");
        	a.setCountry("Føroyar");
        	
        	p.setWorkAddress(a);
        		
        	responseValue.setPersonLookupResponse(p);
        	response.value = responseValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ee.x_road.kli_util_v1.producer.ServiceSoap#testSystem(java.lang.Object body)*
     */
    public java.lang.Object testSystem(java.lang.Object body) { 
        LOG.info("Executing operation testSystem");
        System.out.println(body);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
