package ee.x_road.kli_util_v1.producer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-06-06T11:37:59.865+01:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://kli-util-v1.x-road.ee/producer", name = "ServiceSoap")
@XmlSeeAlso({ee.x_road.xsd.x_road.ObjectFactory.class, ObjectFactory.class, org.w3._2005._05.xmlmime.ObjectFactory.class})
public interface ServiceSoap {

    /**
     * 
     * 			
     */
    @WebMethod(action = "listMethods")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "listMethodsResponse", targetNamespace = "http://x-road.ee/xsd/x-road.xsd", partName = "body")
    public ee.x_road.xsd.x_road.ListMethodsResponse listMethods(
        @WebParam(partName = "body", name = "listMethods", targetNamespace = "http://x-road.ee/xsd/x-road.xsd")
        java.lang.Object body
    );

    /**
     * 
     * 			
     */
    @WebMethod(action = "personLookup")
    @RequestWrapper(localName = "personLookup", targetNamespace = "http://kli-util-v1.x-road.ee/producer", className = "ee.x_road.kli_util_v1.producer.PersonLookup")
    @ResponseWrapper(localName = "personLookupResponse", targetNamespace = "http://kli-util-v1.x-road.ee/producer", className = "ee.x_road.kli_util_v1.producer.PersonLookupResponse")
    public void personLookup(
        @WebParam(name = "request", targetNamespace = "")
        ee.x_road.kli_util_v1.producer.PersonLookup.Request request,
        @WebParam(name = "consumer", targetNamespace = "http://x-road.ee/xsd/x-road.xsd", header = true)
        java.lang.String consumer,
        @WebParam(name = "producer", targetNamespace = "http://x-road.ee/xsd/x-road.xsd", header = true)
        java.lang.String producer,
        @WebParam(name = "userId", targetNamespace = "http://x-road.ee/xsd/x-road.xsd", header = true)
        java.lang.String userId,
        @WebParam(name = "id", targetNamespace = "http://x-road.ee/xsd/x-road.xsd", header = true)
        java.lang.String id,
        @WebParam(name = "service", targetNamespace = "http://x-road.ee/xsd/x-road.xsd", header = true)
        java.lang.String service,
        @WebParam(mode = WebParam.Mode.OUT, name = "request", targetNamespace = "")
        javax.xml.ws.Holder<ee.x_road.kli_util_v1.producer.PersonLookupResponse.Request> request1,
        @WebParam(mode = WebParam.Mode.OUT, name = "response", targetNamespace = "")
        javax.xml.ws.Holder<ee.x_road.kli_util_v1.producer.PersonLookupResponse.Response> response,
        @WebParam(mode = WebParam.Mode.OUT, name = "consumer", targetNamespace = "http://x-road.ee/xsd/x-road.xsd", header = true)
        javax.xml.ws.Holder<java.lang.String> consumer1,
        @WebParam(mode = WebParam.Mode.OUT, name = "producer", targetNamespace = "http://x-road.ee/xsd/x-road.xsd", header = true)
        javax.xml.ws.Holder<java.lang.String> producer1,
        @WebParam(mode = WebParam.Mode.OUT, name = "userId", targetNamespace = "http://x-road.ee/xsd/x-road.xsd", header = true)
        javax.xml.ws.Holder<java.lang.String> userId1,
        @WebParam(mode = WebParam.Mode.OUT, name = "id", targetNamespace = "http://x-road.ee/xsd/x-road.xsd", header = true)
        javax.xml.ws.Holder<java.lang.String> id1,
        @WebParam(mode = WebParam.Mode.OUT, name = "service", targetNamespace = "http://x-road.ee/xsd/x-road.xsd", header = true)
        javax.xml.ws.Holder<java.lang.String> service1
    );

    /**
     * 
     * 			
     */
    @WebMethod(action = "testSystem")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "testSystemResponse", targetNamespace = "http://x-road.ee/xsd/x-road.xsd", partName = "body")
    public java.lang.Object testSystem(
        @WebParam(partName = "body", name = "testSystem", targetNamespace = "http://x-road.ee/xsd/x-road.xsd")
        java.lang.Object body
    );
}
